@startuml

entity エピソード {
    *エピソードID
    --
    *番組ID
    シーズン数
    エピソード数
    *エピソードタイトル
    *エピソード詳細
    *動画時間
    *公開日
}

entity 番組 {
    *番組ID
    --
    *番組タイトル
    *番組詳細
}

entity 番組ジャンル {
    *番組ジャンルID
    --
    *番組ID [FK]
    *ジャンルID[FK]
}

entity ジャンル {
    *ジャンルID
    --
    *ジャンル名
}

entity チャンネル {
    *チャンネルID
    --
    *チャンネル名
}

entity 番組表 {
    *放送ID
    --
    *チャンネルID [FK]
    *エピソードID [FK]
    *視聴数
    *開始時間
    *終了時間
}



番組表 ||--|{ エピソード
番組表 ||-r-|{ チャンネル
エピソード }|-r-|| 番組
番組ジャンル ||--|{ ジャンル
番組 }|--|| 番組ジャンル

@enduml